# -*- coding: utf-8 -*-
"""game project1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1svh903b6VDNrK6XhvxGyw1FDqKsx80tn

ROCK PAPER SCISSOR GAME DEVELOPMENT
"""

import random # importing random module
# Selcet the acscci arts form the perticuler website for better visualization purpose
Rock=("""
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
""")

Paper=("""
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
""")
Scissors=("""
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
""")

game_images=[Rock,Paper,Scissors]#create list
user_choice=int(input("what do you choose? type 0 for Rock,1 for Paper or 2 for Scissors.\n:"))#select the number by user whish
print(game_images[user_choice])
computer_choice= random.randint(0, 2)#random range we can select any number of range or random function
print("computer choose!")
print(game_images[computer_choice]) #call the function with the help of argument
print(f"computer choose {computer_choice}")
if user_choice >=3 or user_choice <0: # python nested if else conditions with or gate
    print("your typed an invalid number")
elif user_choice == 0 and computer_choice == 2:# her we use and gate
    print("user wins!")
elif computer_choice == 0 and user_choice == 2:
    print("your loose!")
elif computer_choice > user_choice:
    print("you lose")
elif user_choice > computer_choice:
    print("you win!")
elif computer_choice == user_choice:
    print("it's draw")